[BUG] VGG16 trained weights loading no longer works with keras 2.0
Info:
File "h5py\h5a.pyx", line 77, in h5py.h5a.open (C:\Minonda\conda-bld\h5py_1474482651427\work\h5py\h5a.c:2193)
KeyError: "Can't open attribute (Can't locate attribute: 'layer_names')

Signed-off-by: Nadith Pathirage <chathurdara@gmail.com>